const MISCRITS_DATA = [
  "Aebex","Agnuf","Aguapogo","Alpha","Ampupine","Aquarion","Aria","Arigato",
  "Auger","Avarus","Babakku","Beakka","Beateorite","Beelzebug","Beetor","Beldame",
  "Blazebit","Blazertooth","Blighted Cubsprout","Blighted Fiender","Blighted Flowerpiller",
  "Blighted Flue","Blighted Kiloray","Blobroller","Bloombat","Bloomple","Blowpuffle",
  "Blub","Bludger","Blug","Boltzee","Boneshee","Boo Blazertooth","Brainzer",
  "Breezycheeks","Bubbles","Budillo","Bunaken","Bunplop","Cadbunny","Casanova",
  "Cerberuff","Charix","Charpy","Crabbles","Craggy","Crickin","Croaky","Cubsprout",
  "Da Windy","Dabee","Daloo","Damse","Dark Aria","Dark Arigato","Dark Auger",
  "Dark Beetor","Dark Breezycheeks","Dark Bubbles","Dark Croaky","Dark Cubsprout",
  "Dark Echino","Dark Eggy","Dark Elefauna","Dark Flameling","Dark Flowerpiller",
  "Dark Flue","Dark Flutterpat","Dark Frostmite","Dark Gippo","Dark Gurgleplops",
  "Dark Hoghedge","Dark Hotfoot","Dark Humbug","Dark Hydroseal","Dark Jellyshock",
  "Dark Kiloray","Dark Lavarilla","Dark Lumera","Dark Luna","Dark Nessy","Dark Owlie",
  "Dark Pillblaze","Dark Poltergust","Dark Prawnja","Dark Quirk","Dark Shellbee",
  "Dark Slithero","Dark Snortus","Dark Sparkitten","Dark Sparkslug","Dark Sparkupine",
  "Dark Spinnerette","Dark Squibee","Dark Squirmle","Dark Steamguin","Dark Tongutail",
  "Dark Treemur","Dark Tulipinny","Dark Twiggum","Dark Vexie","Dark Viperd",
  "Dark Waddles","Dark Weevern","Dark Whik","Deetlee","Defilio","Digsy","Dorux",
  "Dreamger","Drilldent","Drilune","Echino","Eclipso","Eggy","Ekkult","Elefauna",
  "Elphin","Eluzar","Enex","Equestrion","Fangly","Felis","Fennie","Fickra","Fiender",
  "Flaclay","Flameling","Flaring","Flintly","Flowerpiller","Flue","Flurfy","Flurrious",
  "Flutterpat","Foil Croaky","Foil Flintly","Foil Fossillia","Foil Kiloray",
  "Foil Liquifien","Foil Luna","Foil Pamboo","Foil Pangoleaf","Foil Rockodile",
  "Foil Thundercracker","Foil Vexie","Foil Vhisp","Foil Waddles","Fossillia",
  "Freedom","Freezet","Frostmite","Frozy","Fubby","Fungask","Furiko","Gemix",
  "Geneseed","Gippo","Glary","Gog","Goo","Gravitron","Grimm Kiloray","Grubbean",
  "Gurgleplops","Hawkai","Hekatom","Hippoke","Hoghedge","Hoopty","Hotdog","Hotfoot",
  "Humbug","Hydroseal","Ignios","Inferno","Jack","Jellyshock","Kawanko","Keeper",
  "Kelpa","Kiloray","Kitpole","Lagoony","Lambolt","Larbunni","Lavarilla","Lavazard",
  "Leggy","Lheon","Light Bludger","Light Crickin","Light Digsy","Light Flue",
  "Light Flurfy","Light Fossillia","Light Frostmite","Light Grubbean","Light Hawkai",
  "Light Ignios","Light Jack","Light Lavarilla","Light Mumbah","Light Nanaslug",
  "Light Nibbles","Light Quirk","Light Rafiery","Light Slithero","Light Snorkels",
  "Light Sparkspeck","Light Squibee","Light Statikat","Light Tectonyx","Light Twiggum",
  "Light Wavesling","Light Weevern","Light Zaptor","Lil Bubs","Liothning","Liquifien",
  "Lithos","Lumera","Lumite","Luna","Lunako","Lutox","Luvcraft","Magpole","Mama",
  "Manio","Mech","Microblast","Mistraxol","Mooncrit","Moondrip","Mucora","Mumbah",
  "Mun Kee","Nanaslug","Narlope","Nero","Nessy","Nibbles","Niboro","Nubyll","Nyma",
  "Octavio","Oozie","Opigum","Orbling","Orcatide","Osmeron","Owlie","Pachydo","Padma",
  "Pamboo","Pangoleaf","Papa","Patchkin","Peekly","Peepsie","Pennon","Pestling",
  "Phoboros","Pillblaze","Pinplar","Pirate Bludger","Piskie","Pithapillar","Podo",
  "Pollifog","Poltergust","Poppet","Prawnja","Pyras","Pyrex","Quebble","Quirk",
  "Rafiery","Raldio","Rephily","Rexie","Ribos","Rocker Octavio","Rockodile","Rudy",
  "Sapphron","Scarecrow Charix","Shellbee","Shroolet","Shroomer","Shurikoon","Silkire",
  "Skelepup","Skustunk","Sledgehog","Slithero","Smolderfry","Snatcher","Snorkels",
  "Snortus","Sol","Sora","Spangles","Sparkitten","Sparkslug","Sparkspeck","Sparkupine",
  "Spinnerette","Splender","Squawcat","Squibee","Squirmle","Stalkra","Statikat",
  "Steamguin","Tectonyx","Thundercracker","Tongutail","Treemur","Tulipinny","Twiggum",
  "Ursiwave","Valentino","Vamp Skustunk","Vexie","Vhisp","Viperd","Voidotron",
  "Voltombra","Waddles","Warrian","Wavesling","Weevern","Whik","Whispen","Winnebeargo",
  "Woolly","Yuefira","Zappup","Zaptor","Zephry","Zhakor"
];
